# Export Cubase EQ presets as Ardour EQ preset files.
library(XML)

generateCredits<-function(destDir){
  fullPath=paste(destDir,"/LICENSE.txt",sep="")
  cat(file=fullPath,append=FALSE,"\n",sep="")
  cat(file=fullPath,append=TRUE,"AUTHOR: File generated by a code written by Thibault Helleputte, drummer of the \n",sep="")
  cat(file=fullPath,append=TRUE,"  band 'Les Enroules', Belgium, EU, with help from Ben Caby, guitarist of 'Les  \n",sep="")
  cat(file=fullPath,append=TRUE,"  Enroules'.\n",sep="")
  cat(file=fullPath,append=TRUE,"\n\n")  
  cat(file=fullPath,append=TRUE,"  CONTACT: thib at LesEnroules dot Rocks .\n",sep="")
  cat(file=fullPath,append=TRUE,"\n\n")  
  cat(file=fullPath,append=TRUE,"CITATION: Feel free to reuse this code, provided that you give credits to 'Les   \n",sep="")
  cat(file=fullPath,append=TRUE,"  Enroules' by keeping this block of text as such in your files and by liking    \n",sep="")
  cat(file=fullPath,append=TRUE,"  their music/video/material on one of the following media :\n",sep="")
  cat(file=fullPath,append=TRUE,"  - Web: http://LesEnroules.Rocks\n",sep="")
  cat(file=fullPath,append=TRUE,"  - Facebook: https://www.facebook.com/LesEnroules/\n",sep="")
  cat(file=fullPath,append=TRUE,"  - Youtube: https://www.youtube.com/channel/UCl6Q5lQFa6EZphm7TIEN-ew\n",sep="")
  cat(file=fullPath,append=TRUE,"  - Soundcloud: https://soundcloud.com/thib-hell/albums\n",sep="")
  cat(file=fullPath,append=TRUE,"\n\n")
  cat(file=fullPath,append=TRUE,"  LICENSE: GNU LGPL V3 .\n",sep="")
  cat(file=fullPath,append=TRUE,"\n\n")  
}

initiateManifest<-function(destDir){
  fullPath=paste(destDir,"/manifest.ttl",sep="")
  cat(file=fullPath,append=FALSE,"@prefix atom: <http://lv2plug.in/ns/ext/atom#> .\n",sep="")
  cat(file=fullPath,append=TRUE,"@prefix lv2: <http://lv2plug.in/ns/lv2core#> .\n",sep="")
  cat(file=fullPath,append=TRUE,"@prefix pset: <http://lv2plug.in/ns/ext/presets#> .\n",sep="")
  cat(file=fullPath,append=TRUE,"@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n",sep="")
  cat(file=fullPath,append=TRUE,"@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n",sep="")
  cat(file=fullPath,append=TRUE,"@prefix state: <http://lv2plug.in/ns/ext/state#> .\n",sep="")
  cat(file=fullPath,append=TRUE,"@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n",sep="")
  cat(file=fullPath,append=TRUE,"\n",sep="")
  cat(file=fullPath,append=TRUE,"\n",sep="")
}

addToManifest<-function(EQNames,destDir){
  fullPath=paste(destDir,"/manifest.ttl",sep="")
  for(i in EQNames){
    cat(file=fullPath,append=TRUE,"<",gsub(pattern=" ",replacement="_",i),".ttl>\n",sep="")
    cat(file=fullPath,append=TRUE,"		lv2:appliesTo <http://calf.sourceforge.net/plugins/Equalizer8Band> ;\n",sep="")
    cat(file=fullPath,append=TRUE,"		a pset:Preset ;\n",sep="")
    cat(file=fullPath,append=TRUE,"		rdfs:seeAlso <",gsub(pattern=" ",replacement="_",i),".ttl> .\n",sep="")
    cat(file=fullPath,append=TRUE,"\n",sep="")
    cat(file=fullPath,append=TRUE,"\n",sep="")
  }
}

ArdourQValue<-function(CubaseValue){
  # Approximation... 
  return(12*CubaseValue^.95)
}

writeArdourEQPreset<-function(EQName,EQParameters,destDir){
  fileName=paste(gsub(pattern=" ",replacement="_",EQName),".ttl",sep="")
  fullPath=paste(destDir,"/",fileName,sep="")
  # print(paste("Creating ",fullPath,sep=""))
  
  #########################################
  # HEADERS
  #########################################
  
  cat(file=fullPath,append=FALSE,"@prefix atom: <http://lv2plug.in/ns/ext/atom#> .\n")
  cat(file=fullPath,append=TRUE,"@prefix lv2: <http://lv2plug.in/ns/lv2core#> .\n")
  cat(file=fullPath,append=TRUE,"@prefix pset: <http://lv2plug.in/ns/ext/presets#> .\n")
  cat(file=fullPath,append=TRUE,"@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n")
  cat(file=fullPath,append=TRUE,"@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n")
  cat(file=fullPath,append=TRUE,"@prefix state: <http://lv2plug.in/ns/ext/state#> .\n")
  cat(file=fullPath,append=TRUE,"@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n")
  cat(file=fullPath,append=TRUE,"\n")
  cat(file=fullPath,append=TRUE,"<>\n")
  cat(file=fullPath,append=TRUE,"	a pset:Preset ;\n")
  cat(file=fullPath,append=TRUE,"	lv2:appliesTo <http://calf.sourceforge.net/plugins/Equalizer8Band> ;\n")
  cat(file=fullPath,append=TRUE,"	rdfs:label \"",EQName,"\" ;\n",sep="")
  cat(file=fullPath,append=TRUE,"	lv2:port [\n")
  
  #########################################
  # GENERAL PARAMETERS
  #########################################
  
  cat(file=fullPath,append=TRUE,"		lv2:symbol \"analyzer\" ;\n")
  cat(file=fullPath,append=TRUE,"		pset:value 0.0\n")
  cat(file=fullPath,append=TRUE,"	] , [\n")
  cat(file=fullPath,append=TRUE,"		lv2:symbol \"analyzer_mode\" ;\n")
  cat(file=fullPath,append=TRUE,"		pset:value 1.0\n")
  cat(file=fullPath,append=TRUE,"	] , [\n")
  cat(file=fullPath,append=TRUE,"		lv2:symbol \"bypass\" ;\n")
  cat(file=fullPath,append=TRUE,"		pset:value 0.0\n")
  cat(file=fullPath,append=TRUE,"	] , [\n")
  
  #########################################
  # HIGH PASS FILTER
  #########################################
  
  if(format(as.double(EQParameters["Band1","Enable"]),nsmall=1)=="1.0" 
      & format(as.double(EQParameters["Band1","Type"]),nsmall=1)%in%c("2.0","3.0"))
  {
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"hp_active\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 1.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"hp_freq\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value ", EQParameters["Band1","Freq"] ,"\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"hp_mode\" ;\n")
    # 0->12dB/Oct; 1->24dB/Oct; 2->36dB/Oct. Unspecified in Cubase, so 1 by default.
    cat(file=fullPath,append=TRUE,"		pset:value 1.0\n")  
  }
  else
  {
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"hp_active\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 0.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"hp_freq\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 30.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"hp_mode\" ;\n")
    # 0->12dB/Oct; 1->24dB/Oct; 2->36dB/Oct. Unspecified in Cubase, so 1 by default.
    cat(file=fullPath,append=TRUE,"		pset:value 1.0\n")
  }
  
  #########################################
  # HIGH SHELF FILTER
  #########################################
  
  if(format(as.double(EQParameters["Band4","Enable"]),nsmall=1)=="1.0" 
     & format(as.double(EQParameters["Band4","Type"]),nsmall=1)%in%c("1.0","5.0","6.0","7.0"))
  {
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"hs_active\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 1.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"hs_freq\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value ", EQParameters["Band4","Freq"] ,"\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"hs_level\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value ", 10^(as.double(EQParameters["Band4","Gain"])/20) ,"\n")
    cat(file=fullPath,append=TRUE,"	] , [\n") 
  }
  else
  {
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"hs_active\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 0.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"hs_freq\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 5000.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"hs_level\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 1.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n") 
  }

  #########################################
  # OTHER GENERAL PARAMETERS
  #########################################
  
  cat(file=fullPath,append=TRUE,"		lv2:symbol \"individuals\" ;\n")
  cat(file=fullPath,append=TRUE,"		pset:value 1.0\n")
  cat(file=fullPath,append=TRUE,"	] , [\n")
  cat(file=fullPath,append=TRUE,"		lv2:symbol \"level_in\" ;\n")
  cat(file=fullPath,append=TRUE,"		pset:value 1.0\n")
  cat(file=fullPath,append=TRUE,"	] , [\n")
  cat(file=fullPath,append=TRUE,"		lv2:symbol \"level_out\" ;\n")
  cat(file=fullPath,append=TRUE,"		pset:value 1.0\n")
  cat(file=fullPath,append=TRUE,"	] , [\n")
  
  #########################################
  # LOW PASS FILTER
  #########################################
  
  if(format(as.double(EQParameters["Band4","Enable"]),nsmall=1)=="1.0" 
     & format(as.double(EQParameters["Band4","Type"]),nsmall=1)%in%c("2.0","3.0"))
  {
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"lp_active\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 1.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"lp_freq\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value ", EQParameters["Band4","Freq"] ,"\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"lp_mode\" ;\n")
    # 0->12dB/Oct; 1->24dB/Oct; 2->36dB/Oct. Unspecified in Cubase, so 1 by default.
    cat(file=fullPath,append=TRUE,"		pset:value 1.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")        
  }
  else
  {
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"lp_active\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 0.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"lp_freq\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 18000.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"lp_mode\" ;\n")
    # 0->12dB/Oct; 1->24dB/Oct; 2->36dB/Oct. Unspecified in Cubase, so 1 by default.
    cat(file=fullPath,append=TRUE,"		pset:value 1.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")    
  }

  
  #########################################
  # LOW SHELF FILTER
  #########################################
  
  if(format(as.double(EQParameters["Band1","Enable"]),nsmall=1)=="1.0" 
     & format(as.double(EQParameters["Band1","Type"]),nsmall=1)%in%c("1.0","5.0","6.0","7.0"))
  {
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"ls_active\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 1.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"ls_freq\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value ", EQParameters["Band1","Freq"] ,"\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"ls_level\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value ", 10^(as.double(EQParameters["Band1","Gain"])/20) ,"\n")
    cat(file=fullPath,append=TRUE,"	] , [\n") 
  }
  else
  {
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"ls_active\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 0.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"ls_freq\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 100.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"ls_level\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 1.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n") 
  }
  
  #########################################
  # BAND FILTER 1
  #########################################
  
  if(format(as.double(EQParameters["Band1","Enable"]),nsmall=1)=="1.0" 
     & format(as.double(EQParameters["Band1","Type"]),nsmall=1)%in%c("0.0","4.0"))
  {
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"p1_active\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 1.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"p1_freq\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value ", EQParameters["Band1","Freq"] ,"\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"p1_level\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value ", 10^(as.double(EQParameters["Band1","Gain"])/20) ,"\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"p1_q\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value ", ArdourQValue(as.double(EQParameters["Band1","Q"])) ,"\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
  }
  else
  {
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"p1_active\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 0.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"p1_freq\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 100.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"p1_level\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 1.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"p1_q\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 0.1\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
  }

  
  #########################################
  # BAND FILTER 2
  #########################################
  
  cat(file=fullPath,append=TRUE,"		lv2:symbol \"p2_active\" ;\n")
  cat(file=fullPath,append=TRUE,"		pset:value ", format(as.double(EQParameters["Band2","Enable"]),nsmall=1) ,"\n",sep="")
  cat(file=fullPath,append=TRUE,"	] , [\n")
  cat(file=fullPath,append=TRUE,"		lv2:symbol \"p2_freq\" ;\n")
  cat(file=fullPath,append=TRUE,"		pset:value ", EQParameters["Band2","Freq"] ,"\n",sep="")
  cat(file=fullPath,append=TRUE,"	] , [\n")
  cat(file=fullPath,append=TRUE,"		lv2:symbol \"p2_level\" ;\n")
  cat(file=fullPath,append=TRUE,"		pset:value ", 10^(as.double(EQParameters["Band2","Gain"])/20) ,"\n",sep="")
  cat(file=fullPath,append=TRUE,"	] , [\n")
  cat(file=fullPath,append=TRUE,"		lv2:symbol \"p2_q\" ;\n")
  cat(file=fullPath,append=TRUE,"		pset:value ", ArdourQValue(as.double(EQParameters["Band2","Q"])) ,"\n",sep="")
  cat(file=fullPath,append=TRUE,"	] , [\n")
  
  #########################################
  # BAND FILTER 3
  #########################################
  
  cat(file=fullPath,append=TRUE,"		lv2:symbol \"p3_active\" ;\n")
  cat(file=fullPath,append=TRUE,"		pset:value ", format(as.double(EQParameters["Band3","Enable"]),nsmall=1) ,"\n",sep="")
  cat(file=fullPath,append=TRUE,"	] , [\n")
  cat(file=fullPath,append=TRUE,"		lv2:symbol \"p3_freq\" ;\n")
  cat(file=fullPath,append=TRUE,"		pset:value ", EQParameters["Band3","Freq"] ,"\n",sep="")
  cat(file=fullPath,append=TRUE,"	] , [\n")
  cat(file=fullPath,append=TRUE,"		lv2:symbol \"p3_level\" ;\n")
  cat(file=fullPath,append=TRUE,"		pset:value ", 10^(as.double(EQParameters["Band3","Gain"])/20) ,"\n",sep="")
  cat(file=fullPath,append=TRUE,"	] , [\n")
  cat(file=fullPath,append=TRUE,"		lv2:symbol \"p3_q\" ;\n")
  cat(file=fullPath,append=TRUE,"		pset:value ", ArdourQValue(as.double(EQParameters["Band3","Q"])) ,"\n",sep="")
  cat(file=fullPath,append=TRUE,"	] , [\n")
  
  #########################################
  # BAND FILTER 4
  #########################################
  
  if(format(as.double(EQParameters["Band4","Enable"]),nsmall=1)=="1.0" 
     & format(as.double(EQParameters["Band4","Type"]),nsmall=1)%in%c("0.0","4.0"))
  {
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"p4_active\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 1.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"p4_freq\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value ", EQParameters["Band4","Freq"] ,"\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"p4_level\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value ", 10^(as.double(EQParameters["Band4","Gain"])/20) ,"\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"p4_q\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value ", ArdourQValue(as.double(EQParameters["Band4","Q"])) ,"\n")
    cat(file=fullPath,append=TRUE,"	] , [\n") 
  }
  else
  {
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"p4_active\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 0.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"p4_freq\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 5000.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"p4_level\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 1.0\n")
    cat(file=fullPath,append=TRUE,"	] , [\n")
    cat(file=fullPath,append=TRUE,"		lv2:symbol \"p4_q\" ;\n")
    cat(file=fullPath,append=TRUE,"		pset:value 0.1\n")
    cat(file=fullPath,append=TRUE,"	] , [\n") 
  }
  
  #########################################
  # OTHER GENERAL PARAMETER
  #########################################
  
  cat(file=fullPath,append=TRUE,"		lv2:symbol \"zoom\" ;\n")
  cat(file=fullPath,append=TRUE,"		pset:value 0.25\n")
  cat(file=fullPath,append=TRUE,"	] .\n")
  cat(file=fullPath,append=TRUE,"\n")
}

writeArdourEQPresets<-function(listEQPresets,destDir){
  cat("Generating Credits file.\n")
  generateCredits(destDir)
  cat("Initiating manifest.ttl\n")
  initiateManifest(destDir)
  cat("Writing EQ Presets\n")
  for(i in 1:length(listEQPresets)){
    cat("Progress: ",round(100*i/length(listEQPresets)),"%\r",sep="")
    writeArdourEQPreset(names(listEQPresets)[i],listEQPresets[[i]],destDir)
    addToManifest(names(listEQPresets)[i],destDir)
  }
}

##### Script:
# CubasePresets=readCubasePresets("VstEqPreset.pxml")
# writeArdourEQPresets(CubasePresets,destDir = "~/Documents/Musique/Berklee - Coursera - Art of Music Production/Technology of Music Production/Assignment3/Cubase2Ardour/Output/")